- name: Playbook to setup docker and docker compose
  hosts: localhost
  remote_user: root

  vars:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    docker_compose_script: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64

  tasks:
  - name: Ensure docker repository is configured
    copy:
      src: files/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Ensure epel repositiory is present
    yum:
      name: epel-release
      state: present
      update_cache: true

  - name: Re cache all repositiory
    package_facts:
      manager: auto

  - name: Ensure docker compose is setup
    get_url:
      url: "{{ docker_compose_script }}"
      dest: /bin/docker-compose
      mode: 0755

  - name: Ensure containerd.io is installed
    yum:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      state: present

  - name: Ensure docker is installed
    shell: yum install --nobest docker-ce -y 

  - name: Ensure docker service is up and running
    service:
      name: docker
      state: started
      enabled: true
