- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - vars.yml

  tasks:
  - name: Create new droplet
    digital_ocean_droplet:
        state: present
        name: test1
        oauth_token: "{{ TOKEN }}"
        size: 4gb
        ssh_keys: 28018755
        unique_name: true
        region: nyc1
        image: fedora-32-x64
    register: my_droplet

  - name: Debug the Ip Address out
    debug: 
      msg: "IpAddress is {{ my_droplet.data.ip_address }} "

  - name: Add ssh key inside the droplet
    digital_ocean_sshkey:
        name: cloud_key
        oauth_token: "{{ TOKEN }}"
        ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqhH5sWlIfJHhrjNp/mIxYuSS/suEQLUS1ZQKlihs07Jb5YiWrN0j7aXwYoECaVtbD3S1J5uwq9MJUqNHw6btCeKC34J8qg8m2vRW7SswnEJdasoHB3h9c9TVjdlukr9cOD/k80PRXCk2DTmDUngPUGJFzN8e6I2R0U/iOYm3npxk5zxfui7NQ/Vq1dVfZNQ5rUuDlySwgRgVuRXn9QQZmgo6ULu1DLe6Rtl6MwAqQ3GFE57B/xhBoBzfoEBMpJRZIzswTqD4OXm4YVlAbO3uXeC25L5NtqNKI0G7wM7fu3z+7q+6QF4FsVlo3a87Ea3cko2cm4okFtfS+kwvyJXf3PHRPou6DcFT6HXEAG8Qp8YnPmAHIm3KDvaEAPE43ZcJSTZuDJSMWOelYmMZk2ylel5oqKIya5QlQ0l/q6QqVRT//kYMhUuwnwTadBGFf3R3BiUuY8WDw4SIYTIxaSEhgyLE00I9z2hCABvoNBoD2y5ZEp8B3pOgPUXtvDrUJ9Lk= nivedv@homelab.redhat.com"
        state: present

