apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels: 
    type: sample-voting-app
spec: 
  ports: 
    - port: 6379
      targetPort: 6379
  selector: 
    name: redis-deploy
    type: sample-voting-app
    
