apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-app-deploy
  labels: 
    name: worker-app-deploy
    type: sample-voting-app
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: worker-app-deploy
      type: sample-voting-app
  template: 
    metadata: 
      name: worker-app
      labels: 
        name: worker-app-deploy
        type: sample-voting-app
    spec: 
      containers: 
        - name: workerapp
          image: dockersamples/examplevotingapp_worker

