- name: Playbook to setup docker and docker compose
  hosts: localhost
  remote_user: root

  vars:
    docker_script: https://get.docker.com/
    docker_compose_script: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64

  tasks:

  - name: Ensure Docker repo is present
    copy:
      src: files/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.docker-ce.repo

  - name: Ensure docker is installed 
    yum:
      name: docker-ce
      state: present

  - name: Ensure docker service is enabled and running
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure docker compose is installed
    get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
